# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuretype',
            name='othersrs',
            field=models.CharField(blank=True, default='EPSG:3857', help_text='Comma separated list of alternative Spatial Reference Systems to which database-persisted coordinates may be transformed.', max_length=1020, null=True),
        ),
    ]
