# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfs', '0002_featuretype_othersrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolutionFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_resolution', models.FloatField(db_index=True, help_text='The minimal resolution at which to apply the additional query filter.')),
                ('query', models.TextField(default='{}', help_text='JSON containing the query to be passed to a Django queryset .filter()')),
                ('featuretype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfs.FeatureType')),
            ],
        ),
    ]
